// Mocks generated by Mockito 5.4.6 from annotations
// in plantid/test/providers/scan_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:plantid/models/care_advice.dart' as _i2;
import 'package:plantid/models/plant_result.dart' as _i5;
import 'package:plantid/services/openfarm_service.dart' as _i6;
import 'package:plantid/services/plantnet_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCareAdvice_0 extends _i1.SmartFake implements _i2.CareAdvice {
  _FakeCareAdvice_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlantNetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantNetService extends _i1.Mock implements _i3.PlantNetService {
  MockPlantNetService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.PlantResult?> identifyPlant(String? imagePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #identifyPlant,
          [imagePath],
        ),
        returnValue: _i4.Future<_i5.PlantResult?>.value(),
      ) as _i4.Future<_i5.PlantResult?>);
}

/// A class which mocks [OpenFarmService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenFarmService extends _i1.Mock implements _i6.OpenFarmService {
  MockOpenFarmService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CareAdvice> getCareAdvice(String? plantName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCareAdvice,
          [plantName],
        ),
        returnValue: _i4.Future<_i2.CareAdvice>.value(_FakeCareAdvice_0(
          this,
          Invocation.method(
            #getCareAdvice,
            [plantName],
          ),
        )),
      ) as _i4.Future<_i2.CareAdvice>);
}
